repos:
  - repo: local
    hooks:
      - id: make-scripts-executable
        name: Make script files executable
        entry: bash -c 'git add --chmod=+x build-helper.bash cowpatch.sh'
        language: system
        files: '(build-helper\.bash|cowpatch\.sh)$'
        pass_filenames: false

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.11.0
    hooks:
      - id: zizmor

  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.10.0
    hooks:
      - id: shellcheck
        args: ["--severity=warning"] # Optionally only show errors and warnings
        files: "build-helper.bash"

  - repo: https://github.com/pecigonzalo/pre-commit-shfmt
    rev: v2.2.0
    hooks:
      - id: shell-fmt
        args: ["-ci", "-sr", "-i", "0"]
